# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bp1z64Qt0gkuDV80JA18IKgSp7xGY6Kp
"""

n=int(input("Enter the number"))
factorial = 1
for i in range(1,n+1): 
     factorial = factorial*i
print("The factorial of",n,"is",factorial)

